### PR TITLE
Handle changes to comparison parsing in Julia 0.5. Fixes #36

### LINKED ISSUE #36: Update for parsing changes on julia 0.5
Ref https://github.com/JuliaOpt/JuMP.jl/pull/711
One-sided comparisons parse as ``:call`` expressions in Julia 0.5. JuMP follows the new syntax on 0.5 for expressions returned through the MPB interface.

Before:
```
julia> dump(:(x <= 1))
Expr 
  head: Symbol comparison
  args: Array(Any,(3,))
    1: Symbol x
    2: Symbol <=
    3: Int64 1
  typ: Any
```

After:
```
julia> dump(:(x <= 1))
Expr
  head: Symbol call
  args: Array(Any,(3,))
    1: Symbol <=
    2: Symbol x
    3: Int64 1
  typ: Any
```

### PR DESCRIPTION
**Pull request by JackDunnNZ**

### CODE REVIEW

**Comment by mlubin** [comment]
Reran CI with the new CoinOptServices release. Seems like things are failing just because https://github.com/JuliaOpt/CoinOptServices.jl/pull/17 isn't merged yet. Should be safe to merge and tag this, no?

**Comment by JackDunnNZ** [comment]
Yes, it should be good to go

**Comment by mlubin** [comment]
I thought we'd be ok now, but there's a weird homebrew failure on OS X: https://travis-ci.org/JuliaOpt/AmplNLWriter.jl/jobs/130608677#L265
CC @tkelman @staticfloat

**Comment by staticfloat** [comment]
Mmm, looks like I have to update some formulae for new syntax.

**Comment by staticfloat** [comment]
Retry now?

**Comment by mlubin** [comment]
Thanks @staticfloat. I'm still getting a [similar error](https://travis-ci.org/JuliaOpt/AmplNLWriter.jl/jobs/130608678#L246).

Also Cbc decided to compile itself instead of using homebrew:
```
Error: Formulae found in multiple taps: 
 * staticfloat/juliadeps/cbc
 * staticfloat/juliatranslated/cbc
Please use the fully-qualified name e.g. staticfloat/juliadeps/cbc to refer the formula.
Error: Formulae found in multiple taps: 
 * staticfloat/juliadeps/cbc
 * staticfloat/juliatranslated/cbc
```

**Comment by staticfloat** [comment]
Thanks Miles, this is great feedback.  I've pushed a fix in https://github.com/JuliaLang/Homebrew.jl/commit/25c098a39f382741b2a83852443c1e9f143c3f53, I'll tag a new version of `Homebrew.jl` soon, and then ask you to retry this.

**Comment by staticfloat** [comment]
Good catch Miles, the `cbc` thing was happening because I wasn't fully specifying the path to `libgfortran` within the `fixup_libgfortran` postinstall step.  This has been fixed in https://github.com/staticfloat/homebrew-juliadeps/commit/80b59264b3c6e91cf3118024ccc33dff60845907

**Comment by mlubin** [comment]
We have green. Thanks @staticfloat!

**Comment by mlubin** [comment]
Definitely time to tag this

**Pull request merged**
