### PR TITLE
bump MPB and update JuMP syntax

### PR DESCRIPTION
**Pull request by mlubin**

### CODE REVIEW

**Comment by JackDunnNZ** [comment]
Thanks!

**Comment by mlubin** [comment]
I think this package will be untestable until a new CoinOptServices is tagged?
CC @tkelman

**Comment by JackDunnNZ** [comment]
If we get around to pulling out the Bonmin/Couenne binaries into separate packages this won't happen anymore...

**Comment by mlubin** [comment]
Oh, it's untestable because we haven't released a version of JuMP that works with MPB 0.5

**Pull request merged**
