### PR TITLE
Fix error with NLExpr in JuMP 0.12. Closes #29

### LINKED ISSUE #29: Failure with JuMP
I get an UndefVarError when running JuMP master + AmplNLWriter. 
In the following problem, this happens with IpoptNLSolver, whilst IpoptSolver works:
```julia
using JuMP, Ipopt, AmplNLWriter

m = Model(solver=IpoptNLSolver()) # Fails
# m = Model(solver=IpoptSolver()) # Works
n = 30

l = -ones(n); l[1] = 0
u = ones(n)
@defVar(m, l[i] <= x[i=1:n] <= u[i])
@defNLExpr(m, f1, x[1])
@defNLExpr(m, g, 1 + 9*sum{x[j]^2, j=2:n}/(n-1))
@defNLExpr(m, h, 1 - (f1/g)^2)
@defNLExpr(m, f2, g*h)

setValue(x[1], 1)
setValue(x[2:n], zeros(n-1))
@setNLObjective(m, :Min, f2)
solve(m)
```
The error is:
```julia
ERROR: UndefVarError: x not defined
 in eval at /home/riseth/.julia/v0.4/AmplNLWriter/src/AmplNLWriter.jl:1
 in pull_up_constants at /home/riseth/.julia/v0.4/AmplNLWriter/src/nl_linearity.jl:123
 in map! at abstractarray.jl:1277
 in map! at abstractarray.jl:1274
 in pull_up_constants at /home/riseth/.julia/v0.4/AmplNLWriter/src/nl_linearity.jl:125
 in map! at abstractarray.jl:1277
 in map! at abstractarray.jl:1274
 in pull_up_constants at /home/riseth/.julia/v0.4/AmplNLWriter/src/nl_linearity.jl:125
 in map! at abstractarray.jl:1277
 in map! at abstractarray.jl:1274
 in pull_up_constants at /home/riseth/.julia/v0.4/AmplNLWriter/src/nl_linearity.jl:125
 in map! at abstractarray.jl:1277
 in map! at abstractarray.jl:1274
 in pull_up_constants at /home/riseth/.julia/v0.4/AmplNLWriter/src/nl_linearity.jl:125
 in process_expression! at /home/riseth/.julia/v0.4/AmplNLWriter/src/AmplNLWriter.jl:367
 in loadproblem! at /home/riseth/.julia/v0.4/AmplNLWriter/src/AmplNLWriter.jl:210
 in _buildInternalModel_nlp at /home/riseth/.julia/v0.4/JuMP/src/nlp.jl:924
 in buildInternalModel at /home/riseth/.julia/v0.4/JuMP/src/solvers.jl:307
 in solve at /home/riseth/.julia/v0.4/JuMP/src/solvers.jl:131
```

### PR DESCRIPTION
**Pull request by JackDunnNZ**
Don't merge until JuMP 0.12 is tagged

---

@anriseth This fixes #29 for me, can you confirm?

### CODE REVIEW

**Comment by anriseth** [comment]
Yeah, that sorts it out @JackDunnNZ, thanks.

**Comment by JackDunnNZ** [comment]
Great, thanks for reporting it!

**Comment by mlubin** [comment]
Also passing

**Comment by JackDunnNZ** [comment]
Thanks for keeping track of them!

**Pull request merged**
