### PR TITLE
Allow removing of temp files

### PR DESCRIPTION
**Pull request by jcheyns**

### CODE REVIEW

**Comment by mlubin** [comment]
I'm confused about why this is an issue. `m.probfile` should contain a unique filename if you haven't manually overwitten the filename when creating the `AmplNLSolver`.

**Comment by jcheyns** [comment]
I am looping over 30k instances of the same model, each time changing NL
parameters. Several times I had failures because the mv statement couldn’t
overwrite the destination. So the filename is not unique?

**Comment by mlubin** [comment]
What operating system are you using?

**Comment by jcheyns** [comment]
Windows :-(

**Comment by mlubin** [comment]
Could you try recording the values of `m.probfile` to see if it actually repeats during the 30k instances? That would be surprising. It seems more likely that windows doesn't get a chance to fully close `f_prob` before it it asked to move the backed file, and moving open files causes issues I believe.

**Comment by jcheyns** [comment]
I will try.
That does sound familiar, did have such an issue a decade ago and had to
solve with a sleep statement, really

**Comment by jcheyns** [comment]
I simply logged the m.probfile names in teh AmplNLWriter itself.  The file names m.probfile are not unique.  In this test I had 19000 serial solves of a model, 14633 had a file name that occured only once, fot the others a filenmae was reused. I no longer have an error trying to overwrite the destination. Of course Heisenberg could be at play here, due to the extra time needed for logging Windows might have enough time to close the file handle as @mlubin mentioned above.
Fundamentally though, is there anything against the remove_destination flag being on? I guess there is a case with the debug flag being on, the remove_destination flag would remove the file that should have been kept (in case the names are equal).

**Comment by mlubin** [comment]
Thanks for looking into this. Repeating names of temporary files is a bit troubling, but given that this shouldn't affect most users I'm willing to merge. Can you add an inline comment referencing the discussion in this issue for future reference?

**Comment by jcheyns** [comment]
Well, [GetTempFileName ](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364991(v=vs.85).aspx) does not literally guarantee complete uniqueness.
particularly 

> Due to the algorithm used to generate file names, GetTempFileName can perform poorly when creating a large number of files with the same prefix. In such cases, it is recommended that you construct unique file names based on GUIDs.

 
I do agree it is probably a quirk in Windows.
So no concern in case debug flag is on and looping? In that case the files will be deleted...

**Comment by mlubin** [comment]
This change doesn't affect any cases that would have run successfully anyway, so I'm not concerned about the debug flag.

**Comment by jcheyns** [comment]
@mlubin Very practical question to add the comment in the code. Do I close this pull request and create a new one?

**Comment by mlubin** [comment]
No, anything you push to this branch is immediately part of the PR

**Pull request merged**
