### PR TITLE
Remove broken deprecation

### PR DESCRIPTION
**Pull request by joehuchette**
@JackDunnNZ does this seem alright?

### CODE REVIEW

**Comment by JackDunnNZ** [comment]
I'm confused, the deprecation was because we changed from `Dict` to `ASCIIString[]` for the options which this change breaks? 

Did you want to add `AmplNLSolver(solver_command, filename)`? In which case that method can be added and leave the deprecation around?

Maybe I'm missing something

**Comment by joehuchette** [comment]
Currently, the deprecated code doesn't work, since ``Dict{ASCIIString,}()`` isn't a valid constructor. The docs suggest to use the ``AmplNLWriter("couenne")`` type constructor, which falls back to this broken deprecated method. I think there's merit to having a "no-options" constructor of this form, as opposed to ``AmplNLWriter("couenne", ASCIIString[])``, so rather than just fix the deprecation and update the docs, I added the new constructor and deleted the deprecated method. Does this seem reasonable?

**Comment by JackDunnNZ** [comment]
Okay, I see. Yeah that makes sense, it's been deprecated a while now so should be good to go!

**Comment by joehuchette** [comment]
Thanks! Mind if I tag a new release?

**Comment by JackDunnNZ** [comment]
Go for it!

**Pull request merged**
